# coding: utf-8

"""
    SERVCore NG

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 4.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class Message(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, message_text=None, message_code=None):
        """
        Message - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'message_text': 'str',
            'message_code': 'str'
        }

        self.attribute_map = {
            'message_text': 'MESSAGE_TEXT',
            'message_code': 'MESSAGE_CODE'
        }

        self._message_text = message_text
        self._message_code = message_code

    @property
    def message_text(self):
        """
        Gets the message_text of this Message.
        Mensagem de resposta

        :return: The message_text of this Message.
        :rtype: str
        """
        return self._message_text

    @message_text.setter
    def message_text(self, message_text):
        """
        Sets the message_text of this Message.
        Mensagem de resposta

        :param message_text: The message_text of this Message.
        :type: str
        """

        self._message_text = message_text

    @property
    def message_code(self):
        """
        Gets the message_code of this Message.
        REQUIRED_FIELD(-1)<br> INVALID_DATA(-2)<br>GENERAL_EXCEPTION(-3)<br>BUSINESS_EXCEPTION(-4)<br>TIMEOUT_EXCEPTION(-5)<br>SYSTEM_EXCEPTION(-6)

        :return: The message_code of this Message.
        :rtype: str
        """
        return self._message_code

    @message_code.setter
    def message_code(self, message_code):
        """
        Sets the message_code of this Message.
        REQUIRED_FIELD(-1)<br> INVALID_DATA(-2)<br>GENERAL_EXCEPTION(-3)<br>BUSINESS_EXCEPTION(-4)<br>TIMEOUT_EXCEPTION(-5)<br>SYSTEM_EXCEPTION(-6)

        :param message_code: The message_code of this Message.
        :type: str
        """

        self._message_code = message_code

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
