=begin
#SERVCore NG

#No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 4.1

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'date'

module SwaggerClient

  class ModelIn
    # (Obrigatório) Identificação da Transação<br>8000 - Obtêm a lista de senhas<br>8001 - Solicita uma senha
    attr_accessor :trn

    # (Obrigatório) Canal a ser acessado<br>1 - CRM<br>2 - GONDOLA<br>3 - FEEDBACK<br>4 - MOBILE<br>5 - GESTÃO<br>6 - BACKOFFICE<br>7 - SORTEXT
    attr_accessor :chn

    # (Opcional) Instituição de acesso. Caso não seja informado será considerada a instituição default do sistema.
    attr_accessor :inst

    # (Obrigatório) Sigla da loja.
    attr_accessor :unit

    # Categoria do setor.<br>Para transação 8000 o campo é opcional, caso o mesmo não seja informado serão retornadas senhas para todas as categorias.<br>Para transação 8001 o campo é obrigatório.
    attr_accessor :cat

    # (Opcional) Campo utilizado apenas para transação 8001.<br>0 - não retorna a lista de senhas (Default).<br>1 - Retorna a lista de senhas para a categoria e a loja informada.<br>2 - Retorna a lista de senhas para todas as categorias e a loja informada.
    attr_accessor :filter

    # (Opcional) Prioridade da senha.<br>0 - Normal<br>1 - Prioritária<br>Para transação 8000 caso o mesmo não seja informado serão retornadas todas as senhas indepentende da prioridade.<br>Para a transação 8001 caso o mesmo não seja informado será solicitada uma senha com prioridade normal.
    attr_accessor :prior

    # (Opcional) Token seguro gerado pelo FCM (Firebase Cloud Messaging).<br>Caso não seja informado nenhuma notificação será enviada para um cliente Web ou Dispositivo IOS/Android.
    attr_accessor :token

    # (Opcional) Regra de notificação via FCM.<br>Caso o campo não seja informado o valor padrão será X.<br>Campo é composto por uma lógica binária:<br>bit 0 - 1 - notificar ou 0 - não notificar<br>bit 1 2 3 - número de senhas para ser notificado.<br>Exemplos:<br>0 1 0 - será notificado 2 senhas antes da solicitada.<br>0 1 1 -  será notificado 3 senhas antes da solicitada.<br>bit 4 - 0 - notificação sem som 1 - notificação com som.
    attr_accessor :_not


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'trn' => :'trn',
        :'chn' => :'chn',
        :'inst' => :'inst',
        :'unit' => :'unit',
        :'cat' => :'cat',
        :'filter' => :'filter',
        :'prior' => :'prior',
        :'token' => :'token',
        :'_not' => :'not'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'trn' => :'Float',
        :'chn' => :'Float',
        :'inst' => :'Float',
        :'unit' => :'String',
        :'cat' => :'Float',
        :'filter' => :'Float',
        :'prior' => :'Float',
        :'token' => :'String',
        :'_not' => :'Float'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'trn')
        self.trn = attributes[:'trn']
      end

      if attributes.has_key?(:'chn')
        self.chn = attributes[:'chn']
      end

      if attributes.has_key?(:'inst')
        self.inst = attributes[:'inst']
      end

      if attributes.has_key?(:'unit')
        self.unit = attributes[:'unit']
      end

      if attributes.has_key?(:'cat')
        self.cat = attributes[:'cat']
      end

      if attributes.has_key?(:'filter')
        self.filter = attributes[:'filter']
      end

      if attributes.has_key?(:'prior')
        self.prior = attributes[:'prior']
      end

      if attributes.has_key?(:'token')
        self.token = attributes[:'token']
      end

      if attributes.has_key?(:'not')
        self._not = attributes[:'not']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          trn == o.trn &&
          chn == o.chn &&
          inst == o.inst &&
          unit == o.unit &&
          cat == o.cat &&
          filter == o.filter &&
          prior == o.prior &&
          token == o.token &&
          _not == o._not
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [trn, chn, inst, unit, cat, filter, prior, token, _not].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
