/**
 * SERVCore NG
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Message;
import io.swagger.client.model.OutputData;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * DataOut
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-09-19T22:43:24.169Z")
public class DataOut   {
  @SerializedName("OUTPUT_DATA")
  private OutputData OUTPUT_DATA = null;

  @SerializedName("MESSAGE")
  private List<Message> MESSAGE = new ArrayList<Message>();

  @SerializedName("EXCEPTION")
  private List<Message> EXCEPTION = new ArrayList<Message>();

  @SerializedName("RESPONSE_CODE")
  private BigDecimal RESPONSE_CODE = null;

  public DataOut OUTPUT_DATA(OutputData OUTPUT_DATA) {
    this.OUTPUT_DATA = OUTPUT_DATA;
    return this;
  }

   /**
   * Dados de saída
   * @return OUTPUT_DATA
  **/
  @ApiModelProperty(example = "null", value = "Dados de saída")
  public OutputData getOUTPUTDATA() {
    return OUTPUT_DATA;
  }

  public void setOUTPUTDATA(OutputData OUTPUT_DATA) {
    this.OUTPUT_DATA = OUTPUT_DATA;
  }

  public DataOut MESSAGE(List<Message> MESSAGE) {
    this.MESSAGE = MESSAGE;
    return this;
  }

  public DataOut addMESSAGEItem(Message MESSAGEItem) {
    this.MESSAGE.add(MESSAGEItem);
    return this;
  }

   /**
   * (Opcional) Pode ser retornado mais de uma mensagem, porém para os serviços aqui descritos será retornado somente uma mensagem.<br><br>MESSAGE_CODE MESSAGE_TEXT TRANSAÇÃO<br>-4 INVALID_CHANNEL Todas<br>-4 INVALID_IF Todas<br>-4 INVALID_TRANSACTION Todas<br>-4 INVALID_UNIT Todas<br>-4 INVALID_CATEGORY Todas<br>-4 INVALID_PRIORITY Todas<br>-4 TRANSACTION_NOT_PERMMITED Todas<br>-4 QUEUE_EMPTY 8000<br><br>OBS. Quando o campo MESSAGE é retornado o RESPONSE_CODE será 1.
   * @return MESSAGE
  **/
  @ApiModelProperty(example = "null", value = "(Opcional) Pode ser retornado mais de uma mensagem, porém para os serviços aqui descritos será retornado somente uma mensagem.<br><br>MESSAGE_CODE MESSAGE_TEXT TRANSAÇÃO<br>-4 INVALID_CHANNEL Todas<br>-4 INVALID_IF Todas<br>-4 INVALID_TRANSACTION Todas<br>-4 INVALID_UNIT Todas<br>-4 INVALID_CATEGORY Todas<br>-4 INVALID_PRIORITY Todas<br>-4 TRANSACTION_NOT_PERMMITED Todas<br>-4 QUEUE_EMPTY 8000<br><br>OBS. Quando o campo MESSAGE é retornado o RESPONSE_CODE será 1.")
  public List<Message> getMESSAGE() {
    return MESSAGE;
  }

  public void setMESSAGE(List<Message> MESSAGE) {
    this.MESSAGE = MESSAGE;
  }

  public DataOut EXCEPTION(List<Message> EXCEPTION) {
    this.EXCEPTION = EXCEPTION;
    return this;
  }

  public DataOut addEXCEPTIONItem(Message EXCEPTIONItem) {
    this.EXCEPTION.add(EXCEPTIONItem);
    return this;
  }

   /**
   * (Opcional) Quando acontece uma exceção tratada ou não tratada.<br><br>MESSAGE_CODE MESSAGE_TEXT TRANSAÇÃO<br>-3 Exception tratada Todas<br>-3 GENERIC_ERROR Todas<br>OBS. Quando o campo EXCEPTION é retornado o RESPONSE_CODE é -1.
   * @return EXCEPTION
  **/
  @ApiModelProperty(example = "null", value = "(Opcional) Quando acontece uma exceção tratada ou não tratada.<br><br>MESSAGE_CODE MESSAGE_TEXT TRANSAÇÃO<br>-3 Exception tratada Todas<br>-3 GENERIC_ERROR Todas<br>OBS. Quando o campo EXCEPTION é retornado o RESPONSE_CODE é -1.")
  public List<Message> getEXCEPTION() {
    return EXCEPTION;
  }

  public void setEXCEPTION(List<Message> EXCEPTION) {
    this.EXCEPTION = EXCEPTION;
  }

  public DataOut RESPONSE_CODE(BigDecimal RESPONSE_CODE) {
    this.RESPONSE_CODE = RESPONSE_CODE;
    return this;
  }

   /**
   * UNSUCCESSFULLY(-1)<br>SUCCESSFULLY(0)<br>SUCCESSFULLY_WARNING(1)<br>SUCCESSFULLY_EMPTY_DATA(2)
   * @return RESPONSE_CODE
  **/
  @ApiModelProperty(example = "null", value = "UNSUCCESSFULLY(-1)<br>SUCCESSFULLY(0)<br>SUCCESSFULLY_WARNING(1)<br>SUCCESSFULLY_EMPTY_DATA(2)")
  public BigDecimal getRESPONSECODE() {
    return RESPONSE_CODE;
  }

  public void setRESPONSECODE(BigDecimal RESPONSE_CODE) {
    this.RESPONSE_CODE = RESPONSE_CODE;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataOut dataOut = (DataOut) o;
    return Objects.equals(this.OUTPUT_DATA, dataOut.OUTPUT_DATA) &&
        Objects.equals(this.MESSAGE, dataOut.MESSAGE) &&
        Objects.equals(this.EXCEPTION, dataOut.EXCEPTION) &&
        Objects.equals(this.RESPONSE_CODE, dataOut.RESPONSE_CODE);
  }

  @Override
  public int hashCode() {
    return Objects.hash(OUTPUT_DATA, MESSAGE, EXCEPTION, RESPONSE_CODE);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataOut {\n");
    
    sb.append("    OUTPUT_DATA: ").append(toIndentedString(OUTPUT_DATA)).append("\n");
    sb.append("    MESSAGE: ").append(toIndentedString(MESSAGE)).append("\n");
    sb.append("    EXCEPTION: ").append(toIndentedString(EXCEPTION)).append("\n");
    sb.append("    RESPONSE_CODE: ").append(toIndentedString(RESPONSE_CODE)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

