/**
 * SERVCore NG
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;


/**
 * In
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-09-19T22:43:24.169Z")
public class In   {
  @SerializedName("trn")
  private BigDecimal trn = null;

  @SerializedName("chn")
  private BigDecimal chn = null;

  @SerializedName("inst")
  private BigDecimal inst = null;

  @SerializedName("unit")
  private String unit = null;

  @SerializedName("cat")
  private BigDecimal cat = null;

  @SerializedName("filter")
  private BigDecimal filter = null;

  @SerializedName("prior")
  private BigDecimal prior = null;

  @SerializedName("token")
  private String token = null;

  @SerializedName("not")
  private BigDecimal not = null;

  public In trn(BigDecimal trn) {
    this.trn = trn;
    return this;
  }

   /**
   * (Obrigatório) Identificação da Transação<br>8000 - Obtêm a lista de senhas<br>8001 - Solicita uma senha
   * @return trn
  **/
  @ApiModelProperty(example = "null", value = "(Obrigatório) Identificação da Transação<br>8000 - Obtêm a lista de senhas<br>8001 - Solicita uma senha")
  public BigDecimal getTrn() {
    return trn;
  }

  public void setTrn(BigDecimal trn) {
    this.trn = trn;
  }

  public In chn(BigDecimal chn) {
    this.chn = chn;
    return this;
  }

   /**
   * (Obrigatório) Canal a ser acessado<br>1 - CRM<br>2 - GONDOLA<br>3 - FEEDBACK<br>4 - MOBILE<br>5 - GESTÃO<br>6 - BACKOFFICE<br>7 - SORTEXT
   * @return chn
  **/
  @ApiModelProperty(example = "null", value = "(Obrigatório) Canal a ser acessado<br>1 - CRM<br>2 - GONDOLA<br>3 - FEEDBACK<br>4 - MOBILE<br>5 - GESTÃO<br>6 - BACKOFFICE<br>7 - SORTEXT")
  public BigDecimal getChn() {
    return chn;
  }

  public void setChn(BigDecimal chn) {
    this.chn = chn;
  }

  public In inst(BigDecimal inst) {
    this.inst = inst;
    return this;
  }

   /**
   * (Opcional) Instituição de acesso. Caso não seja informado será considerada a instituição default do sistema.
   * @return inst
  **/
  @ApiModelProperty(example = "null", value = "(Opcional) Instituição de acesso. Caso não seja informado será considerada a instituição default do sistema.")
  public BigDecimal getInst() {
    return inst;
  }

  public void setInst(BigDecimal inst) {
    this.inst = inst;
  }

  public In unit(String unit) {
    this.unit = unit;
    return this;
  }

   /**
   * (Obrigatório) Sigla da loja.
   * @return unit
  **/
  @ApiModelProperty(example = "null", value = "(Obrigatório) Sigla da loja.")
  public String getUnit() {
    return unit;
  }

  public void setUnit(String unit) {
    this.unit = unit;
  }

  public In cat(BigDecimal cat) {
    this.cat = cat;
    return this;
  }

   /**
   * Categoria do setor.<br>Para transação 8000 o campo é opcional, caso o mesmo não seja informado serão retornadas senhas para todas as categorias.<br>Para transação 8001 o campo é obrigatório.
   * @return cat
  **/
  @ApiModelProperty(example = "null", value = "Categoria do setor.<br>Para transação 8000 o campo é opcional, caso o mesmo não seja informado serão retornadas senhas para todas as categorias.<br>Para transação 8001 o campo é obrigatório.")
  public BigDecimal getCat() {
    return cat;
  }

  public void setCat(BigDecimal cat) {
    this.cat = cat;
  }

  public In filter(BigDecimal filter) {
    this.filter = filter;
    return this;
  }

   /**
   * (Opcional) Campo utilizado apenas para transação 8001.<br>0 - não retorna a lista de senhas (Default).<br>1 - Retorna a lista de senhas para a categoria e a loja informada.<br>2 - Retorna a lista de senhas para todas as categorias e a loja informada.
   * @return filter
  **/
  @ApiModelProperty(example = "null", value = "(Opcional) Campo utilizado apenas para transação 8001.<br>0 - não retorna a lista de senhas (Default).<br>1 - Retorna a lista de senhas para a categoria e a loja informada.<br>2 - Retorna a lista de senhas para todas as categorias e a loja informada.")
  public BigDecimal getFilter() {
    return filter;
  }

  public void setFilter(BigDecimal filter) {
    this.filter = filter;
  }

  public In prior(BigDecimal prior) {
    this.prior = prior;
    return this;
  }

   /**
   * (Opcional) Prioridade da senha.<br>0 - Normal<br>1 - Prioritária<br>Para transação 8000 caso o mesmo não seja informado serão retornadas todas as senhas indepentende da prioridade.<br>Para a transação 8001 caso o mesmo não seja informado será solicitada uma senha com prioridade normal.
   * @return prior
  **/
  @ApiModelProperty(example = "null", value = "(Opcional) Prioridade da senha.<br>0 - Normal<br>1 - Prioritária<br>Para transação 8000 caso o mesmo não seja informado serão retornadas todas as senhas indepentende da prioridade.<br>Para a transação 8001 caso o mesmo não seja informado será solicitada uma senha com prioridade normal.")
  public BigDecimal getPrior() {
    return prior;
  }

  public void setPrior(BigDecimal prior) {
    this.prior = prior;
  }

  public In token(String token) {
    this.token = token;
    return this;
  }

   /**
   * (Opcional) Token seguro gerado pelo FCM (Firebase Cloud Messaging).<br>Caso não seja informado nenhuma notificação será enviada para um cliente Web ou Dispositivo IOS/Android.
   * @return token
  **/
  @ApiModelProperty(example = "null", value = "(Opcional) Token seguro gerado pelo FCM (Firebase Cloud Messaging).<br>Caso não seja informado nenhuma notificação será enviada para um cliente Web ou Dispositivo IOS/Android.")
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public In not(BigDecimal not) {
    this.not = not;
    return this;
  }

   /**
   * (Opcional) Regra de notificação via FCM.<br>Caso o campo não seja informado o valor padrão será X.<br>Campo é composto por uma lógica binária:<br>bit 0 - 1 - notificar ou 0 - não notificar<br>bit 1 2 3 - número de senhas para ser notificado.<br>Exemplos:<br>0 1 0 - será notificado 2 senhas antes da solicitada.<br>0 1 1 -  será notificado 3 senhas antes da solicitada.<br>bit 4 - 0 - notificação sem som 1 - notificação com som.
   * @return not
  **/
  @ApiModelProperty(example = "null", value = "(Opcional) Regra de notificação via FCM.<br>Caso o campo não seja informado o valor padrão será X.<br>Campo é composto por uma lógica binária:<br>bit 0 - 1 - notificar ou 0 - não notificar<br>bit 1 2 3 - número de senhas para ser notificado.<br>Exemplos:<br>0 1 0 - será notificado 2 senhas antes da solicitada.<br>0 1 1 -  será notificado 3 senhas antes da solicitada.<br>bit 4 - 0 - notificação sem som 1 - notificação com som.")
  public BigDecimal getNot() {
    return not;
  }

  public void setNot(BigDecimal not) {
    this.not = not;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    In in = (In) o;
    return Objects.equals(this.trn, in.trn) &&
        Objects.equals(this.chn, in.chn) &&
        Objects.equals(this.inst, in.inst) &&
        Objects.equals(this.unit, in.unit) &&
        Objects.equals(this.cat, in.cat) &&
        Objects.equals(this.filter, in.filter) &&
        Objects.equals(this.prior, in.prior) &&
        Objects.equals(this.token, in.token) &&
        Objects.equals(this.not, in.not);
  }

  @Override
  public int hashCode() {
    return Objects.hash(trn, chn, inst, unit, cat, filter, prior, token, not);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class In {\n");
    
    sb.append("    trn: ").append(toIndentedString(trn)).append("\n");
    sb.append("    chn: ").append(toIndentedString(chn)).append("\n");
    sb.append("    inst: ").append(toIndentedString(inst)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    cat: ").append(toIndentedString(cat)).append("\n");
    sb.append("    filter: ").append(toIndentedString(filter)).append("\n");
    sb.append("    prior: ").append(toIndentedString(prior)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    not: ").append(toIndentedString(not)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

