/**
 * SERVCore NG
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Message
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-09-19T22:43:24.169Z")
public class Message   {
  @SerializedName("MESSAGE_TEXT")
  private String MESSAGE_TEXT = null;

  @SerializedName("MESSAGE_CODE")
  private String MESSAGE_CODE = null;

  public Message MESSAGE_TEXT(String MESSAGE_TEXT) {
    this.MESSAGE_TEXT = MESSAGE_TEXT;
    return this;
  }

   /**
   * Mensagem de resposta
   * @return MESSAGE_TEXT
  **/
  @ApiModelProperty(example = "null", value = "Mensagem de resposta")
  public String getMESSAGETEXT() {
    return MESSAGE_TEXT;
  }

  public void setMESSAGETEXT(String MESSAGE_TEXT) {
    this.MESSAGE_TEXT = MESSAGE_TEXT;
  }

  public Message MESSAGE_CODE(String MESSAGE_CODE) {
    this.MESSAGE_CODE = MESSAGE_CODE;
    return this;
  }

   /**
   * REQUIRED_FIELD(-1)<br> INVALID_DATA(-2)<br>GENERAL_EXCEPTION(-3)<br>BUSINESS_EXCEPTION(-4)<br>TIMEOUT_EXCEPTION(-5)<br>SYSTEM_EXCEPTION(-6)
   * @return MESSAGE_CODE
  **/
  @ApiModelProperty(example = "null", value = "REQUIRED_FIELD(-1)<br> INVALID_DATA(-2)<br>GENERAL_EXCEPTION(-3)<br>BUSINESS_EXCEPTION(-4)<br>TIMEOUT_EXCEPTION(-5)<br>SYSTEM_EXCEPTION(-6)")
  public String getMESSAGECODE() {
    return MESSAGE_CODE;
  }

  public void setMESSAGECODE(String MESSAGE_CODE) {
    this.MESSAGE_CODE = MESSAGE_CODE;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Message message = (Message) o;
    return Objects.equals(this.MESSAGE_TEXT, message.MESSAGE_TEXT) &&
        Objects.equals(this.MESSAGE_CODE, message.MESSAGE_CODE);
  }

  @Override
  public int hashCode() {
    return Objects.hash(MESSAGE_TEXT, MESSAGE_CODE);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Message {\n");
    
    sb.append("    MESSAGE_TEXT: ").append(toIndentedString(MESSAGE_TEXT)).append("\n");
    sb.append("    MESSAGE_CODE: ").append(toIndentedString(MESSAGE_CODE)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

