/**
 * SERVCore NG
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;


/**
 * Queue
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-09-19T22:43:24.169Z")
public class Queue   {
  @SerializedName("n")
  private String n = null;

  @SerializedName("cat")
  private BigDecimal cat = null;

  @SerializedName("prior")
  private BigDecimal prior = null;

  public Queue n(String n) {
    this.n = n;
    return this;
  }

   /**
   * Senha.
   * @return n
  **/
  @ApiModelProperty(example = "null", value = "Senha.")
  public String getN() {
    return n;
  }

  public void setN(String n) {
    this.n = n;
  }

  public Queue cat(BigDecimal cat) {
    this.cat = cat;
    return this;
  }

   /**
   * Categoria.
   * @return cat
  **/
  @ApiModelProperty(example = "null", value = "Categoria.")
  public BigDecimal getCat() {
    return cat;
  }

  public void setCat(BigDecimal cat) {
    this.cat = cat;
  }

  public Queue prior(BigDecimal prior) {
    this.prior = prior;
    return this;
  }

   /**
   * Prioridade.
   * @return prior
  **/
  @ApiModelProperty(example = "null", value = "Prioridade.")
  public BigDecimal getPrior() {
    return prior;
  }

  public void setPrior(BigDecimal prior) {
    this.prior = prior;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Queue queue = (Queue) o;
    return Objects.equals(this.n, queue.n) &&
        Objects.equals(this.cat, queue.cat) &&
        Objects.equals(this.prior, queue.prior);
  }

  @Override
  public int hashCode() {
    return Objects.hash(n, cat, prior);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Queue {\n");
    
    sb.append("    n: ").append(toIndentedString(n)).append("\n");
    sb.append("    cat: ").append(toIndentedString(cat)).append("\n");
    sb.append("    prior: ").append(toIndentedString(prior)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

