---
swagger: "2.0"
info:
  version: "4.1"
  title: "SERVCore NG"
host: "diebold.herokuapp.com"
basePath: "/servcorews"
schemes:
- "https"
- "http"
produces:
- "application/json"
paths:
  /processJSON:
    post:
      tags:
      - "Queue"
      description: "Serviços de gestão de filas\n"
      operationId: "processJSONPOST"
      parameters:
      - in: "body"
        name: "in"
        description: "JSON com o POST."
        required: true
        schema:
          $ref: "#/definitions/In"
      responses:
        200:
          description: "Resposta com Sucesso"
          schema:
            $ref: "#/definitions/out"
      x-swagger-router-controller: "Queue"
definitions:
  In:
    type: "string"
    properties:
      trn:
        type: "number"
        description: "(Obrigatório) Identificação da Transação<br>8000 - Obtêm a lista\
          \ de senhas<br>8001 - Solicita uma senha"
      chn:
        type: "number"
        description: "(Obrigatório) Canal a ser acessado<br>1 - CRM<br>2 - GONDOLA<br>3\
          \ - FEEDBACK<br>4 - MOBILE<br>5 - GESTÃO<br>6 - BACKOFFICE<br>7 - SORTEXT"
      inst:
        type: "number"
        description: "(Opcional) Instituição de acesso. Caso não seja informado será\
          \ considerada a instituição default do sistema."
      unit:
        type: "string"
        description: "(Obrigatório) Sigla da loja."
      cat:
        type: "number"
        description: "Categoria do setor.<br>Para transação 8000 o campo é opcional,\
          \ caso o mesmo não seja informado serão retornadas senhas para todas as\
          \ categorias.<br>Para transação 8001 o campo é obrigatório."
      filter:
        type: "number"
        description: "(Opcional) Campo utilizado apenas para transação 8001.<br>0\
          \ - não retorna a lista de senhas (Default).<br>1 - Retorna a lista de senhas\
          \ para a categoria e a loja informada.<br>2 - Retorna a lista de senhas\
          \ para todas as categorias e a loja informada."
      prior:
        type: "number"
        description: "(Opcional) Prioridade da senha.<br>0 - Normal<br>1 - Prioritá\
          ria<br>Para transação 8000 caso o mesmo não seja informado serão retornadas\
          \ todas as senhas indepentende da prioridade.<br>Para a transação 8001 caso\
          \ o mesmo não seja informado será solicitada uma senha com prioridade normal."
      token:
        type: "string"
        description: "(Opcional) Token seguro gerado pelo FCM (Firebase Cloud Messaging).<br>Caso\
          \ não seja informado nenhuma notificação será enviada para um cliente Web\
          \ ou Dispositivo IOS/Android."
      not:
        type: "number"
        description: "(Opcional) Regra de notificação via FCM.<br>Caso o campo nã\
          o seja informado o valor padrão será X.<br>Campo é composto por uma lógica\
          \ binária:<br>bit 0 - 1 - notificar ou 0 - não notificar<br>bit 1 2 3 -\
          \ número de senhas para ser notificado.<br>Exemplos:<br>0 1 0 - será notificado\
          \ 2 senhas antes da solicitada.<br>0 1 1 -  será notificado 3 senhas antes\
          \ da solicitada.<br>bit 4 - 0 - notificação sem som 1 - notificação com\
          \ som."
  message:
    properties:
      MESSAGE_TEXT:
        type: "string"
        description: "Mensagem de resposta"
      MESSAGE_CODE:
        type: "string"
        description: "REQUIRED_FIELD(-1)<br>\tINVALID_DATA(-2)<br>GENERAL_EXCEPTION(-3)<br>BUSINESS_EXCEPTION(-4)<br>TIMEOUT_EXCEPTION(-5)<br>SYSTEM_EXCEPTION(-6)"
  dataOut:
    properties:
      OUTPUT_DATA:
        description: "Dados de saída"
        $ref: "#/definitions/outputData"
      MESSAGE:
        type: "array"
        description: "(Opcional) Pode ser retornado mais de uma mensagem, porém para\
          \ os serviços aqui descritos será retornado somente uma mensagem.<br><br>MESSAGE_CODE\
          \ MESSAGE_TEXT TRANSAÇÃO<br>-4 INVALID_CHANNEL Todas<br>-4 INVALID_IF Todas<br>-4\
          \ INVALID_TRANSACTION Todas<br>-4 INVALID_UNIT Todas<br>-4 INVALID_CATEGORY\
          \ Todas<br>-4 INVALID_PRIORITY Todas<br>-4 TRANSACTION_NOT_PERMMITED Todas<br>-4\
          \ QUEUE_EMPTY 8000<br><br>OBS. Quando o campo MESSAGE é retornado o RESPONSE_CODE\
          \ será 1."
        items:
          $ref: "#/definitions/message"
      EXCEPTION:
        type: "array"
        description: "(Opcional) Quando acontece uma exceção tratada ou não tratada.<br><br>MESSAGE_CODE\
          \ MESSAGE_TEXT TRANSAÇÃO<br>-3 Exception tratada Todas<br>-3 GENERIC_ERROR\
          \ Todas<br>OBS. Quando o campo EXCEPTION é retornado o RESPONSE_CODE é -1."
        items:
          $ref: "#/definitions/message"
      RESPONSE_CODE:
        type: "number"
        description: "UNSUCCESSFULLY(-1)<br>SUCCESSFULLY(0)<br>SUCCESSFULLY_WARNING(1)<br>SUCCESSFULLY_EMPTY_DATA(2)"
  outputData:
    properties:
      queues:
        type: "array"
        description: "Lista de senhas atual.<br>Para transação 8000 este campo sempre\
          \ será retornado baseado no filtro de entrada<br>Para a transação 8001 este\
          \ campo será retornado baseado no campo filter."
        items:
          $ref: "#/definitions/queue"
      queue:
        description: "Senha obtida para a loja, categoria e prioridade informada.<br>Este\
          \ campo só é retornado para a transação 8001."
        $ref: "#/definitions/queue"
  queue:
    properties:
      n:
        type: "string"
        description: "Senha."
      cat:
        type: "number"
        description: "Categoria."
      prior:
        type: "number"
        description: "Prioridade."
  out:
    properties:
      data:
        description: "Dados de saída"
        $ref: "#/definitions/dataOut"
